apiVersion: v1
kind: Secret
metadata:
  name: taskflow-secrets
  namespace: taskflow
type: Opaque
stringData:
  JWT_SECRET: <JWT_SECRET>
  DATABASE_URL_USERS: postgresql://taskflow:<DB_PASSWORD>@<RDS_ADDRESS>:5432/users_db
  DATABASE_URL_PROJECTS: postgresql://taskflow:<DB_PASSWORD>@<RDS_ADDRESS>:5432/projects_db
  DATABASE_URL_ACTIVITIES: postgresql://taskflow:<DB_PASSWORD>@<RDS_ADDRESS>:5432/activities_db
