apiVersion: v1
kind: Secret
metadata:
  name: taskflow-secrets
  namespace: taskflow
type: Opaque
stringData:
  JWT_SECRET: dev-secret-change-me
  POSTGRES_USER: taskflow
  POSTGRES_PASSWORD: taskflow
  DATABASE_URL_USERS: postgresql://taskflow:taskflow@postgres:5432/users_db
  DATABASE_URL_PROJECTS: postgresql://taskflow:taskflow@postgres:5432/projects_db
  DATABASE_URL_ACTIVITIES: postgresql://taskflow:taskflow@postgres:5432/activities_db
